### ISSUE TITLE
Cannons plugin can't pass BlockExplodeEvent to OD

### ISSUE THREAD

**Issue by HunterGPlays** [drtshock/ObsidianDestroyer#29] opened 2015-06-28 11:59 UTC
I am running the latest versions of Cannons and ObsidianDestroyer. The server is running version 1.8.7-R0.1-SNAPSHOT.

https://gist.github.com/HunterGPlays/42d1356031477848342f

**Comment by drtshock** [comment] 2015-06-28 22:22
Duplicate of https://github.com/drtshock/ObsidianDestroyer/issues/27

**Closed by drtshock** 2015-06-28 22:22 UTC
