### ISSUE TITLE
BlockExplodeEvent error reporting (when using cannons)

### ISSUE THREAD

**Issue by AwaaX** [drtshock/ObsidianDestroyer#31] opened 2015-06-30 20:25 UTC
Hello,
This error occur when the tnt of the cannon from the cannons plugin touch the obsdian wall and explode :
http://pastebin.com/d0Wm0Lpr

The explosion is not good with Obsidian destroyer and is good when obsidian destroyer isn't enable : 
![screen_with_od](https://cloud.githubusercontent.com/assets/8031531/8441105/9a4ffd28-1f76-11e5-9994-c6521a27076c.png)
![screen_without_od](https://cloud.githubusercontent.com/assets/8031531/8441106/9a5467f0-1f76-11e5-8cde-760a3973d3c0.png)

Can you fix that fast please?
Sorry for my bad english i'm french :)

**Comment by drtshock** [comment] 2015-06-30 20:51
Duplicate of https://github.com/drtshock/ObsidianDestroyer/issues/27

**Closed by drtshock** 2015-06-30 20:51 UTC

**Comment by AwaaX** [comment] 2015-07-02 23:50
Same pictures and same error! Not fixed :
BlockExplodeEvent problem to ObsidianDestroyer 4.3.10
http://pastebin.com/dJLjaADu

**Comment by drtshock** [comment] 2015-07-03 00:01
jeez. there's another commit to fix that NPE.

**Comment by AwaaX** [comment] 2015-07-03 00:22
I have difficulties for recompile can you update at spigotmc.org ?

**Comment by AwaaX** [comment] 2015-07-03 00:59
It's done, but why the explosion is little when i have ObsidianDestroyer and why it's big when i unload ObsidianDestroyer when use Cannons plugin? (looks my pictures at the top)
